name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "GitHub Action"
          git lfs install
          git remote add space https://oauth2:$HF_TOKEN@huggingface.co/spaces/dkumi12/handwritten-cnn
          git push --force space main
